### ISSUE TITLE
Add pre-commit configuration for basic commit scans

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/site-scanning#145]
As an engineer, so that I'm assured I'm only committing content that's free of any secrets (keys, tokens, etc.) or any git artifacts (e.g., incomplete merges), I would like a mechanism to perform scans prior to creating git commits.

There are a variety of tools that can be used to perform this, one of which is [pre-commit](https://pre-commit.com/).  It accepts a configuration that developers may opt-in to using (via `pre-commit` install).

The following is a `.pre-commit-config.yaml` file that I (@wesley-dean-gsa) use on virtually all of my repositories:

```yaml
---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-added-large-files
    - id: check-symlinks

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
    - id: detect-secrets
```

The hooks listed here are very fast, run locally, and may be helpful to most -- if not all -- repositories.  Additionally, there's a [collection of published hooks](https://pre-commit.com/hooks.html) that may be used; moreover, one may create their own hooks if customization is required.

If a developer wishes to use pre-commit, they would:

1. install pre-commit (`pip install pre-commit`)
2. run `pre-commit install` to add the appropriate git hooks (hooks aren't added to the repository for security reasons)
3. if desired, one may update the versions found in the .pre-commit-config.yaml file by running `pre-commit autoupdate`

When running `git commit`, the pre-commit hooks would be called sequentially; if any fail or result in files being changed, the `git commit` will abort and the developer may add make corrections (if necessary) and stage (`git add`) the modified files for being committed.

Note: it's possible to skip the pre-commit hooks at any time by adding the `-n` flag to `git commit`.
