### ISSUE TITLE
Refactor Actions / workflows to make deployment dependent upon test

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/site-scanning#148]
As an engineer, so that I know I'm only deploying code that has passed our tests, I would like to make deployment jobs to be dependent upon successful completion of test jobs.

1. in [test.yml](https://github.com/GSA/site-scanning-engine/blob/1d85a0357199af389400b0e32c9ad8b713679bf3/.github/workflows/test.yml), split the existing `build` job into `build` and `test` jobs
2. provide a `name` to the `test` job that we can reference outside of that workflow
3. in the `dev` environment, incorporate "[wait-on-check-action](https://github.com/marketplace/actions/wait-on-check)" from [Le Wagon's](https://github.com/lewagon) marketplace action:

```YAML
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Run tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
```

Note: `check-name` needs to be replaced with the `name` we provided in the test action previously

4. apply the same to the [prod](https://github.com/GSA/site-scanning-engine/blob/1d85a0357199af389400b0e32c9ad8b713679bf3/.github/workflows/deploy.yml) environment
