### ISSUE TITLE
Fix missing node_modules for Megalinter

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/site-scanning#175]
As an engineer, so that I can have my Node code linted, I would like to ensure that the required modules are available for the Megalinter.

The `.gitignore` file specifically excludes `node_modules/` so that when the Megalinter runs, the modules aren't available.  As a result, files such `eslint.js` that are otherwise used during the linting process are unavailable.

Folks have seen similar behavior before ([example](https://github.com/megalinter/megalinter/issues/1042)) and the recommended approach is to add a `PRE_COMMANDS` section that downloads those modules before Megalinter runs.  

```YAML
PRE_COMMANDS:

  - continue_if_failed: false

    command: npm ci  # or "yarn" if you use yarn

    cwd: workspace
```
