### ISSUE TITLE
Add Snyk scans

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/site-scanning#180]
As a security engineer, so that I can be made aware of potential security vulnerabilities, I would like to add Snyk scanning to our CI/CD workflow.

Snyk is a tool that provides "industry-leading security intelligence."  They provide a free to use level of tooling for open-source projects; it is available as a GitHub action and through Docker Hub (although that's less relevant than the GitHub action).

This is a sample configuration:

```YAML
name: Snyk Scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```

Note: we'll need to supply a Snyk token which is available for free once one [creates an account](https://app.snyk.io/login?cta=sign-up&loc=nav&page=homepage) on Snyk's web site.  We'll need to determine how to handle the account creation from an administrative perspective.
